kafka:
  topic: syslog
server:
  port: 8082
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # 连接数满后的排队数，默认为100
#    accept-count: 1000
#    threads:
#      # tomcat最大线程数，默认为200
#      max: 800
#      # Tomcat启动初始化的线程数，默认值10
#      min-spare: 100

# Spring配置
spring:
  profiles:
    active: common
  application:
    name: application-kafka
  kafka:
#    bootstrap-servers: 10.25.10.16:9092 #这个是kafka的地址,对应你server.properties中配置的
    bootstrap-servers: 10.25.16.130:9092 #这个是kafka的地址,对应你server.properties中配置的
    producer:
      batch-size: 16384 #批量大小
      acks: -1 #应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      retries: 10 # 消息发送重试次数
      #transaction-id-prefix: transaction
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 2000 #提交延迟
          partitioner: #指定分区器
            class: com.wz.jiangsu.wangteng.kafka.partitioner.CustomizePartitioner
#      transaction-id-prefix: tx_
    consumer:
      group-id: sb_group #默认的消费组ID
      enable-auto-commit: true #是否自动提交offset
      auto-commit-interval: 2000 #提交offset延时
      # 当kafka中没有初始offset或offset超出范围时将自动重置offset
      # earliest:重置为分区中最小的offset;
      # latest:重置为分区中最新的offset(消费分区中新产生的数据);
      # none:只要有一个分区不存在已提交的offset,就抛出异常;
      auto-offset-reset: latest
      max-poll-records: 50 #单次拉取消息的最大条数
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session:
          timeout:
            ms: 120000 # 消费会话超时时间（超过这个时间 consumer 没有发送心跳，就会触发 rebalance 操作）
        request:
          timeout:
            ms: 18000 # 消费请求的超时时间
    listener:
      missing-topics-fatal: false # consumer listener topics 不存在时，启动项目就会报错
      type: batch
  # 资源信息
#  messages:
#    # 国际化资源文件路径
#    basename: i18n/messages
#  # 文件上传
#  servlet:
#     multipart:
#       # 单个文件大小
#       max-file-size:  10MB
#       # 设置总上传的文件大小
#       max-request-size:  20MB
  # 服务模块
#  devtools:
#    restart:
#      # 热部署开关
#      enabled: true

# MyBatis配置
#mybatis:
    # 搜索指定包别名
#    typeAliasesPackage: com.zhrj.**.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath:mapper/**/*Mapper.xml
    # 加载全局的配置文件
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
#    configLocation: classpath:mybatis/mybatis-config.xml

#mybatis-plus:
#  configuration:
#    #设置当查询结果值为null时，同样映射该查询字段给map。
#    call-setters-on-nulls: true
#    # 下划线转驼峰
#    map-underscore-to-camel-case: true

